name: Build PHP 8.3

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
env:
  OPERATING_SYS: ubuntu-latest
  PHP_VERSION: 8.3
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: Run Tests
    uses: WebFiori/workflows/.github/workflows/test-php.yaml@v1.1
    with:
      php-version: '8.3'
      phpunit-config: 'tests/phpunit10.xml'
            

  code-coverage:
    name: Coverage
    needs: test
    uses: WebFiori/workflows/.github/workflows/coverage-codecov.yaml@v1.1
    with:
      php-version: '8.3'
      coverage-file: 'php-8.3-coverage.xml'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  

  code-quality:
    name: Code Quality
    needs: test
    uses: WebFiori/workflows/.github/workflows/quality-sonarcloud.yaml@v1.1
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  release-prod:
    name: Prepare Production Release Branch / Publish Release
    needs: [code-coverage, code-quality]
    uses: WebFiori/workflows/.github/workflows/release-php.yaml@v1.1
    with:
      branch: 'main'
